import type { WorkMode } from "@/lib/supabase/types";

export const VERTICALS = [
  "tech",
  "finance",
  "marketing",
  "design",
  "ops",
  "legal",
  "healthcare",
  "education",
  "sales",
  "hr",
  "consulting",
  "property",
  "media",
] as const;
export type VerticalType = (typeof VERTICALS)[number];

export const MAX_PORTFOLIO_PROJECTS = 10;

export const SCORE_TIERS = {
  gold: 90,
  green: 60,
  red: 30,
} as const;

export const WORK_MODES: { value: WorkMode; label: string }[] = [
  { value: "full_time", label: "FULL-TIME" },
  { value: "part_time", label: "PART-TIME" },
  { value: "remote", label: "REMOTE" },
  { value: "internship", label: "INTERNSHIP" },
];

export const NOTICE_PERIODS: { value: number; label: string }[] = [
  { value: 0, label: "IMMEDIATE" },
  { value: 14, label: "2 WEEKS" },
  { value: 30, label: "1 MONTH" },
  { value: 60, label: "2 MONTHS" },
  { value: 90, label: "3+ MONTHS" },
];

export const JOB_ROLES: { title: string; vertical: VerticalType }[] = [
  // tech
  { title: "Fullstack Engineer", vertical: "tech" },
  { title: "Backend Engineer", vertical: "tech" },
  { title: "Mobile Engineer", vertical: "tech" },
  { title: "Senior Frontend Engineer", vertical: "tech" },
  { title: "Data Engineer", vertical: "tech" },
  { title: "ML Engineer", vertical: "tech" },
  { title: "Platform Engineer", vertical: "tech" },
  { title: "Site Reliability Engineer", vertical: "tech" },
  { title: "Security Engineer", vertical: "tech" },
  { title: "Staff Engineer", vertical: "tech" },
  // finance
  { title: "Accountant", vertical: "finance" },
  { title: "Financial Analyst", vertical: "finance" },
  { title: "Compliance Officer", vertical: "finance" },
  { title: "Risk Analyst", vertical: "finance" },
  { title: "Equity Research Analyst", vertical: "finance" },
  { title: "Investment Banking Analyst", vertical: "finance" },
  { title: "Financial Controller", vertical: "finance" },
  { title: "Portfolio Manager", vertical: "finance" },
  // marketing
  { title: "Social Media Manager", vertical: "marketing" },
  { title: "SEO Specialist", vertical: "marketing" },
  { title: "Content Marketing Manager", vertical: "marketing" },
  { title: "Marketing Analyst", vertical: "marketing" },
  { title: "Performance Marketing Manager", vertical: "marketing" },
  { title: "Brand Manager", vertical: "marketing" },
  { title: "Growth Marketing Lead", vertical: "marketing" },
  { title: "Marketing Director", vertical: "marketing" },
  // design
  { title: "Visual Designer", vertical: "design" },
  { title: "UI Designer", vertical: "design" },
  { title: "UX Designer", vertical: "design" },
  { title: "Product Designer", vertical: "design" },
  { title: "UX Researcher", vertical: "design" },
  { title: "Brand Designer", vertical: "design" },
  { title: "Design Systems Lead", vertical: "design" },
  { title: "Design Director", vertical: "design" },
  // ops
  { title: "Logistics Coordinator", vertical: "ops" },
  { title: "Operations Analyst", vertical: "ops" },
  { title: "Supply Chain Analyst", vertical: "ops" },
  { title: "Vendor Manager", vertical: "ops" },
  { title: "Project Manager", vertical: "ops" },
  { title: "Process Improvement Manager", vertical: "ops" },
  { title: "Operations Manager", vertical: "ops" },
  { title: "Operations Director", vertical: "ops" },
  // legal
  { title: "Paralegal", vertical: "legal" },
  { title: "Legal Executive", vertical: "legal" },
  { title: "Legal Counsel", vertical: "legal" },
  { title: "Senior Legal Counsel", vertical: "legal" },
  { title: "Company Secretarial Officer", vertical: "legal" },
  { title: "Compliance Counsel", vertical: "legal" },
  { title: "Head of Legal", vertical: "legal" },
  // healthcare
  { title: "Registered Nurse", vertical: "healthcare" },
  { title: "Enrolled Nurse", vertical: "healthcare" },
  { title: "Pharmacist", vertical: "healthcare" },
  { title: "Physiotherapist", vertical: "healthcare" },
  { title: "Clinical Research Associate", vertical: "healthcare" },
  { title: "Medical Affairs Manager", vertical: "healthcare" },
  { title: "Healthcare Administrator", vertical: "healthcare" },
  // education
  { title: "Teaching Assistant", vertical: "education" },
  { title: "Teacher", vertical: "education" },
  { title: "Senior Teacher", vertical: "education" },
  { title: "Curriculum Developer", vertical: "education" },
  { title: "Admissions Officer", vertical: "education" },
  { title: "Academic Director", vertical: "education" },
  // sales
  { title: "Sales Executive", vertical: "sales" },
  { title: "Account Executive", vertical: "sales" },
  { title: "Business Development Manager", vertical: "sales" },
  { title: "Key Account Manager", vertical: "sales" },
  { title: "Customer Success Manager", vertical: "sales" },
  { title: "Pre-Sales Consultant", vertical: "sales" },
  { title: "Sales Manager", vertical: "sales" },
  { title: "Sales Director", vertical: "sales" },
  // hr
  { title: "HR Officer", vertical: "hr" },
  { title: "Talent Acquisition Specialist", vertical: "hr" },
  { title: "HR Generalist", vertical: "hr" },
  { title: "Compensation & Benefits Specialist", vertical: "hr" },
  { title: "Learning & Development Manager", vertical: "hr" },
  { title: "HR Business Partner", vertical: "hr" },
  { title: "HR Manager", vertical: "hr" },
  { title: "HR Director", vertical: "hr" },
  // consulting
  { title: "Business Analyst", vertical: "consulting" },
  { title: "Associate Consultant", vertical: "consulting" },
  { title: "Management Consultant", vertical: "consulting" },
  { title: "Senior Consultant", vertical: "consulting" },
  { title: "Engagement Manager", vertical: "consulting" },
  { title: "Principal Consultant", vertical: "consulting" },
  // property
  { title: "Leasing Officer", vertical: "property" },
  { title: "Property Officer", vertical: "property" },
  { title: "Quantity Surveyor", vertical: "property" },
  { title: "Building Surveyor", vertical: "property" },
  { title: "Facilities Manager", vertical: "property" },
  { title: "Property Manager", vertical: "property" },
  { title: "Asset Manager", vertical: "property" },
  // media
  { title: "Journalist", vertical: "media" },
  { title: "Editor", vertical: "media" },
  { title: "Video Producer", vertical: "media" },
  { title: "Public Relations Officer", vertical: "media" },
  { title: "PR Manager", vertical: "media" },
  { title: "Communications Director", vertical: "media" },
];

export const SKILLS: { name: string; vertical: VerticalType }[] = [
  // tech
  { name: "JavaScript", vertical: "tech" },
  { name: "TypeScript", vertical: "tech" },
  { name: "React", vertical: "tech" },
  { name: "Node.js", vertical: "tech" },
  { name: "Python", vertical: "tech" },
  { name: "SQL", vertical: "tech" },
  { name: "Cloud / DevOps", vertical: "tech" },
  { name: "System Design", vertical: "tech" },
  { name: "Java", vertical: "tech" },
  { name: "Go", vertical: "tech" },
  { name: "Kubernetes", vertical: "tech" },
  { name: "Machine Learning", vertical: "tech" },
  { name: "Data Engineering", vertical: "tech" },
  { name: "Cybersecurity", vertical: "tech" },
  { name: "Mobile Development", vertical: "tech" },
  { name: "API Design", vertical: "tech" },
  // finance
  { name: "Financial Modeling", vertical: "finance" },
  { name: "Valuation", vertical: "finance" },
  { name: "Accounting", vertical: "finance" },
  { name: "Risk Analysis", vertical: "finance" },
  { name: "Excel / VBA", vertical: "finance" },
  { name: "Bloomberg Terminal", vertical: "finance" },
  { name: "Financial Reporting", vertical: "finance" },
  { name: "Audit", vertical: "finance" },
  { name: "Regulatory Compliance", vertical: "finance" },
  { name: "Credit Analysis", vertical: "finance" },
  { name: "Treasury", vertical: "finance" },
  { name: "M&A", vertical: "finance" },
  { name: "Portfolio Management", vertical: "finance" },
  { name: "Taxation", vertical: "finance" },
  // marketing
  { name: "SEO", vertical: "marketing" },
  { name: "Content Strategy", vertical: "marketing" },
  { name: "Paid Acquisition", vertical: "marketing" },
  { name: "Marketing Analytics", vertical: "marketing" },
  { name: "Brand Strategy", vertical: "marketing" },
  { name: "Copywriting", vertical: "marketing" },
  { name: "Social Media", vertical: "marketing" },
  { name: "Email / CRM Marketing", vertical: "marketing" },
  { name: "Event Marketing", vertical: "marketing" },
  { name: "Market Research", vertical: "marketing" },
  { name: "Growth Strategy", vertical: "marketing" },
  { name: "Media Buying", vertical: "marketing" },
  { name: "Influencer Marketing", vertical: "marketing" },
  { name: "Marketing Automation", vertical: "marketing" },
  // design
  { name: "UI Design", vertical: "design" },
  { name: "UX Research", vertical: "design" },
  { name: "Figma", vertical: "design" },
  { name: "Design Systems", vertical: "design" },
  { name: "Prototyping", vertical: "design" },
  { name: "Visual Design", vertical: "design" },
  { name: "Motion Design", vertical: "design" },
  { name: "Illustration", vertical: "design" },
  { name: "Interaction Design", vertical: "design" },
  { name: "Branding", vertical: "design" },
  { name: "3D Design", vertical: "design" },
  { name: "Adobe Creative Suite", vertical: "design" },
  // ops
  { name: "Project Management", vertical: "ops" },
  { name: "Supply Chain", vertical: "ops" },
  { name: "Process Improvement", vertical: "ops" },
  { name: "Logistics", vertical: "ops" },
  { name: "Vendor Management", vertical: "ops" },
  { name: "Data Analysis", vertical: "ops" },
  { name: "Procurement", vertical: "ops" },
  { name: "Inventory Management", vertical: "ops" },
  { name: "Quality Assurance", vertical: "ops" },
  { name: "Lean / Six Sigma", vertical: "ops" },
  { name: "ERP Systems", vertical: "ops" },
  { name: "Demand Planning", vertical: "ops" },
  // legal
  { name: "Contract Drafting", vertical: "legal" },
  { name: "Legal Research", vertical: "legal" },
  { name: "Corporate Law", vertical: "legal" },
  { name: "Litigation", vertical: "legal" },
  { name: "Regulatory Affairs", vertical: "legal" },
  { name: "Company Secretarial", vertical: "legal" },
  { name: "IP Law", vertical: "legal" },
  { name: "Due Diligence", vertical: "legal" },
  { name: "Employment Law", vertical: "legal" },
  { name: "Data Privacy", vertical: "legal" },
  // healthcare
  { name: "Patient Care", vertical: "healthcare" },
  { name: "Clinical Research", vertical: "healthcare" },
  { name: "Pharmacology", vertical: "healthcare" },
  { name: "Medical Devices", vertical: "healthcare" },
  { name: "Health Informatics", vertical: "healthcare" },
  { name: "Regulatory Submissions", vertical: "healthcare" },
  { name: "Physiotherapy", vertical: "healthcare" },
  { name: "Nursing", vertical: "healthcare" },
  { name: "Medical Writing", vertical: "healthcare" },
  { name: "Public Health", vertical: "healthcare" },
  // education
  { name: "Lesson Planning", vertical: "education" },
  { name: "Curriculum Design", vertical: "education" },
  { name: "Classroom Management", vertical: "education" },
  { name: "EAL / ESL Teaching", vertical: "education" },
  { name: "Student Assessment", vertical: "education" },
  { name: "Educational Technology", vertical: "education" },
  { name: "Special Educational Needs", vertical: "education" },
  { name: "Academic Counseling", vertical: "education" },
  { name: "IB / DSE Curriculum", vertical: "education" },
  { name: "Early Childhood Education", vertical: "education" },
  // sales
  { name: "Lead Generation", vertical: "sales" },
  { name: "Account Management", vertical: "sales" },
  { name: "Negotiation", vertical: "sales" },
  { name: "CRM (Salesforce)", vertical: "sales" },
  { name: "Solution Selling", vertical: "sales" },
  { name: "Sales Forecasting", vertical: "sales" },
  { name: "Channel Management", vertical: "sales" },
  { name: "Client Relationship Management", vertical: "sales" },
  { name: "Cold Outreach", vertical: "sales" },
  { name: "Territory Planning", vertical: "sales" },
  // hr
  { name: "Recruitment", vertical: "hr" },
  { name: "Onboarding", vertical: "hr" },
  { name: "Compensation & Benefits", vertical: "hr" },
  { name: "Employee Relations", vertical: "hr" },
  { name: "HRIS", vertical: "hr" },
  { name: "Performance Management", vertical: "hr" },
  { name: "Learning & Development", vertical: "hr" },
  { name: "Talent Management", vertical: "hr" },
  { name: "Employment Ordinance", vertical: "hr" },
  { name: "Payroll", vertical: "hr" },
  // consulting
  { name: "Strategy Development", vertical: "consulting" },
  { name: "Market Entry", vertical: "consulting" },
  { name: "Business Case Development", vertical: "consulting" },
  { name: "Stakeholder Management", vertical: "consulting" },
  { name: "Change Management", vertical: "consulting" },
  { name: "Process Mapping", vertical: "consulting" },
  { name: "Data Visualization", vertical: "consulting" },
  { name: "Workshop Facilitation", vertical: "consulting" },
  { name: "Commercial Due Diligence", vertical: "consulting" },
  { name: "Storylining / Presentations", vertical: "consulting" },
  // property
  { name: "Leasing", vertical: "property" },
  { name: "Property Management", vertical: "property" },
  { name: "Quantity Surveying", vertical: "property" },
  { name: "Building Surveying", vertical: "property" },
  { name: "Facilities Management", vertical: "property" },
  { name: "Asset Management", vertical: "property" },
  { name: "Property Valuation", vertical: "property" },
  { name: "Tenancy Law", vertical: "property" },
  { name: "Construction Contracts", vertical: "property" },
  { name: "BIM", vertical: "property" },
  // media
  { name: "Journalism", vertical: "media" },
  { name: "Editing", vertical: "media" },
  { name: "Video Production", vertical: "media" },
  { name: "Public Relations", vertical: "media" },
  { name: "Media Relations", vertical: "media" },
  { name: "Scriptwriting", vertical: "media" },
  { name: "Photography", vertical: "media" },
  { name: "Podcast Production", vertical: "media" },
  { name: "Crisis Communications", vertical: "media" },
  { name: "Social Content", vertical: "media" },
];
