import type { WorkMode } from "@/lib/supabase/types";

export const VERTICALS = [
  "consulting",
  "design",
  "education",
  "finance",
  "healthcare",
  "hr",
  "legal",
  "marketing",
  "media",
  "ops",
  "property",
  "sales",
  "tech",
] as const;
export type VerticalType = (typeof VERTICALS)[number];

// Display label for a vertical, uppercased except for a few that spell out
// (the stored value stays the short key to match seed data).
const VERTICAL_LABELS: Partial<Record<VerticalType, string>> = {
  ops: "OPERATIONS",
  hr: "HUMAN RESOURCES",
  tech: "TECHNOLOGY",
};
export function verticalLabel(vertical: VerticalType): string {
  return VERTICAL_LABELS[vertical] ?? vertical.toUpperCase();
}

export const MAX_PORTFOLIO_PROJECTS = 10;

// LinkedIn job posts cap at 10 skills — same limit per posting here
export const MAX_POSTING_SKILLS = 10;

// Accepted matches with no chat activity for this long are auto-ghosted
export const CHAT_GHOST_HOURS = 72;

// Client-side pre-upload validation for chat file attachments — the
// match-files bucket enforces the hard 10MB limit server-side
export const MAX_CHAT_FILE_SIZE_MB = 10;

// Employers can create this many job postings without an active subscription;
// beyond this, POST /api/recruiter-postings requires subscription_status = 'active'
export const FREE_JOB_POSTINGS = 3;

export const COMPANY_SIZES = ["1-10", "11-50", "51-200", "201-1000", "1000+"];

// Country / territory options for citizenship, posting work location, and
// company HQ selects. "Hong Kong" (not "Hong Kong SAR") matches existing
// candidate_job_postings.location seed/data. Sorted A-Z.
export const COUNTRIES: string[] = [
  "Australia", "Austria", "Bangladesh", "Belgium", "Brazil", "Cambodia", "Canada",
  "Chile", "China", "Colombia", "Czechia", "Denmark", "Egypt", "Finland", "France",
  "Germany", "Greece", "Hong Kong", "Hungary", "India", "Indonesia", "Ireland",
  "Israel", "Italy", "Japan", "Jordan", "Kenya", "Kuwait", "Laos", "Macau",
  "Malaysia", "Mexico", "Myanmar", "Nepal", "Netherlands", "New Zealand", "Nigeria",
  "Norway", "Pakistan", "Philippines", "Poland", "Portugal", "Qatar", "Romania",
  "Russia", "Saudi Arabia", "Singapore", "South Africa", "South Korea", "Spain",
  "Sri Lanka", "Sweden", "Switzerland", "Taiwan", "Thailand", "Turkey", "Ukraine",
  "United Arab Emirates", "United Kingdom", "United States", "Vietnam", "Other",
];

// Currency code per country (for the candidate's current-salary input, which
// adapts to their country of residence). Defaults to HKD for unmapped/Other.
const COUNTRY_CURRENCY: Record<string, string> = {
  Australia: "AUD", Austria: "EUR", Bangladesh: "BDT", Belgium: "EUR", Brazil: "BRL",
  Cambodia: "KHR", Canada: "CAD", Chile: "CLP", China: "CNY", Colombia: "COP",
  Czechia: "CZK", Denmark: "DKK", Egypt: "EGP", Finland: "EUR", France: "EUR",
  Germany: "EUR", Greece: "EUR", "Hong Kong": "HKD", Hungary: "HUF", India: "INR",
  Indonesia: "IDR", Ireland: "EUR", Israel: "ILS", Italy: "EUR", Japan: "JPY",
  Jordan: "JOD", Kenya: "KES", Kuwait: "KWD", Laos: "LAK", Macau: "MOP",
  Malaysia: "MYR", Mexico: "MXN", Myanmar: "MMK", Nepal: "NPR", Netherlands: "EUR",
  "New Zealand": "NZD", Nigeria: "NGN", Norway: "NOK", Pakistan: "PKR",
  Philippines: "PHP", Poland: "PLN", Portugal: "EUR", Qatar: "QAR", Romania: "RON",
  Russia: "RUB", "Saudi Arabia": "SAR", Singapore: "SGD", "South Africa": "ZAR",
  "South Korea": "KRW", Spain: "EUR", "Sri Lanka": "LKR", Sweden: "SEK",
  Switzerland: "CHF", Taiwan: "TWD", Thailand: "THB", Turkey: "TRY", Ukraine: "UAH",
  "United Arab Emirates": "AED", "United Kingdom": "GBP", "United States": "USD",
  Vietnam: "VND",
};

export function currencyForCountry(country: string | null | undefined): string {
  return (country && COUNTRY_CURRENCY[country]) || "HKD";
}

// Language options for the candidate biodata languages picker.
export const LANGUAGES: string[] = [
  "Arabic", "Bengali", "Cantonese", "Dutch", "English", "Filipino", "French",
  "German", "Hindi", "Indonesian", "Italian", "Japanese", "Khmer", "Korean",
  "Malay", "Mandarin", "Nepali", "Portuguese", "Punjabi", "Russian", "Spanish",
  "Tamil", "Thai", "Urdu", "Vietnamese",
];

export const SCORE_TIERS = {
  gold: 90,
  green: 60,
  red: 30,
} as const;

export const WORK_MODES: { value: WorkMode; label: string }[] = [
  { value: "full_time", label: "FULL-TIME" },
  { value: "part_time", label: "PART-TIME" },
  { value: "remote", label: "REMOTE" },
  { value: "internship", label: "INTERNSHIP" },
];

export const NOTICE_PERIODS: { value: number; label: string }[] = [
  { value: 0, label: "IMMEDIATE" },
  { value: 14, label: "2 WEEKS" },
  { value: 30, label: "1 MONTH" },
  { value: 60, label: "2 MONTHS" },
  { value: 90, label: "3+ MONTHS" },
];

export const JOB_ROLES: { title: string; vertical: VerticalType }[] = [
  // tech
  { title: "Fullstack Engineer", vertical: "tech" },
  { title: "Backend Engineer", vertical: "tech" },
  { title: "Mobile Engineer", vertical: "tech" },
  { title: "Senior Frontend Engineer", vertical: "tech" },
  { title: "Data Engineer", vertical: "tech" },
  { title: "ML Engineer", vertical: "tech" },
  { title: "Platform Engineer", vertical: "tech" },
  { title: "Site Reliability Engineer", vertical: "tech" },
  { title: "Security Engineer", vertical: "tech" },
  { title: "Staff Engineer", vertical: "tech" },
  // finance
  { title: "Accountant", vertical: "finance" },
  { title: "Financial Analyst", vertical: "finance" },
  { title: "Compliance Officer", vertical: "finance" },
  { title: "Risk Analyst", vertical: "finance" },
  { title: "Equity Research Analyst", vertical: "finance" },
  { title: "Investment Banking Analyst", vertical: "finance" },
  { title: "Financial Controller", vertical: "finance" },
  { title: "Portfolio Manager", vertical: "finance" },
  // marketing
  { title: "Social Media Manager", vertical: "marketing" },
  { title: "SEO Specialist", vertical: "marketing" },
  { title: "Content Marketing Manager", vertical: "marketing" },
  { title: "Marketing Analyst", vertical: "marketing" },
  { title: "Performance Marketing Manager", vertical: "marketing" },
  { title: "Brand Manager", vertical: "marketing" },
  { title: "Growth Marketing Lead", vertical: "marketing" },
  { title: "Marketing Director", vertical: "marketing" },
  // design
  { title: "Visual Designer", vertical: "design" },
  { title: "UI Designer", vertical: "design" },
  { title: "UX Designer", vertical: "design" },
  { title: "Product Designer", vertical: "design" },
  { title: "UX Researcher", vertical: "design" },
  { title: "Brand Designer", vertical: "design" },
  { title: "Design Systems Lead", vertical: "design" },
  { title: "Design Director", vertical: "design" },
  // ops
  { title: "Logistics Coordinator", vertical: "ops" },
  { title: "Operations Analyst", vertical: "ops" },
  { title: "Supply Chain Analyst", vertical: "ops" },
  { title: "Vendor Manager", vertical: "ops" },
  { title: "Project Manager", vertical: "ops" },
  { title: "Process Improvement Manager", vertical: "ops" },
  { title: "Operations Manager", vertical: "ops" },
  { title: "Operations Director", vertical: "ops" },
  // legal
  { title: "Paralegal", vertical: "legal" },
  { title: "Legal Executive", vertical: "legal" },
  { title: "Legal Counsel", vertical: "legal" },
  { title: "Senior Legal Counsel", vertical: "legal" },
  { title: "Company Secretarial Officer", vertical: "legal" },
  { title: "Compliance Counsel", vertical: "legal" },
  { title: "Head of Legal", vertical: "legal" },
  // healthcare
  { title: "Registered Nurse", vertical: "healthcare" },
  { title: "Enrolled Nurse", vertical: "healthcare" },
  { title: "Pharmacist", vertical: "healthcare" },
  { title: "Physiotherapist", vertical: "healthcare" },
  { title: "Clinical Research Associate", vertical: "healthcare" },
  { title: "Medical Affairs Manager", vertical: "healthcare" },
  { title: "Healthcare Administrator", vertical: "healthcare" },
  // education
  { title: "Teaching Assistant", vertical: "education" },
  { title: "Teacher", vertical: "education" },
  { title: "Senior Teacher", vertical: "education" },
  { title: "Curriculum Developer", vertical: "education" },
  { title: "Admissions Officer", vertical: "education" },
  { title: "Academic Director", vertical: "education" },
  // sales
  { title: "Sales Executive", vertical: "sales" },
  { title: "Account Executive", vertical: "sales" },
  { title: "Business Development Manager", vertical: "sales" },
  { title: "Key Account Manager", vertical: "sales" },
  { title: "Customer Success Manager", vertical: "sales" },
  { title: "Pre-Sales Consultant", vertical: "sales" },
  { title: "Sales Manager", vertical: "sales" },
  { title: "Sales Director", vertical: "sales" },
  // hr
  { title: "HR Officer", vertical: "hr" },
  { title: "Talent Acquisition Specialist", vertical: "hr" },
  { title: "HR Generalist", vertical: "hr" },
  { title: "Compensation & Benefits Specialist", vertical: "hr" },
  { title: "Learning & Development Manager", vertical: "hr" },
  { title: "HR Business Partner", vertical: "hr" },
  { title: "HR Manager", vertical: "hr" },
  { title: "HR Director", vertical: "hr" },
  // consulting
  { title: "Business Analyst", vertical: "consulting" },
  { title: "Associate Consultant", vertical: "consulting" },
  { title: "Management Consultant", vertical: "consulting" },
  { title: "Senior Consultant", vertical: "consulting" },
  { title: "Engagement Manager", vertical: "consulting" },
  { title: "Principal Consultant", vertical: "consulting" },
  // property
  { title: "Leasing Officer", vertical: "property" },
  { title: "Property Officer", vertical: "property" },
  { title: "Quantity Surveyor", vertical: "property" },
  { title: "Building Surveyor", vertical: "property" },
  { title: "Facilities Manager", vertical: "property" },
  { title: "Property Manager", vertical: "property" },
  { title: "Asset Manager", vertical: "property" },
  // media
  { title: "Journalist", vertical: "media" },
  { title: "Editor", vertical: "media" },
  { title: "Video Producer", vertical: "media" },
  { title: "Public Relations Officer", vertical: "media" },
  { title: "PR Manager", vertical: "media" },
  { title: "Communications Director", vertical: "media" },
];

export const SKILLS: { name: string; vertical: VerticalType }[] = [
  // tech
  { name: "JavaScript", vertical: "tech" },
  { name: "TypeScript", vertical: "tech" },
  { name: "React", vertical: "tech" },
  { name: "Node.js", vertical: "tech" },
  { name: "Python", vertical: "tech" },
  { name: "SQL", vertical: "tech" },
  { name: "Cloud / DevOps", vertical: "tech" },
  { name: "System Design", vertical: "tech" },
  { name: "Java", vertical: "tech" },
  { name: "Go", vertical: "tech" },
  { name: "Kubernetes", vertical: "tech" },
  { name: "Machine Learning", vertical: "tech" },
  { name: "Data Engineering", vertical: "tech" },
  { name: "Cybersecurity", vertical: "tech" },
  { name: "Mobile Development", vertical: "tech" },
  { name: "API Design", vertical: "tech" },
  { name: "C++", vertical: "tech" },
  { name: "C#", vertical: "tech" },
  { name: "PHP", vertical: "tech" },
  { name: "Swift", vertical: "tech" },
  { name: "Kotlin", vertical: "tech" },
  { name: "Flutter", vertical: "tech" },
  { name: "React Native", vertical: "tech" },
  { name: "Next.js", vertical: "tech" },
  { name: "Vue.js", vertical: "tech" },
  { name: "Angular", vertical: "tech" },
  { name: "GraphQL", vertical: "tech" },
  { name: "AWS", vertical: "tech" },
  { name: "Azure", vertical: "tech" },
  { name: "Google Cloud Platform", vertical: "tech" },
  { name: "Docker", vertical: "tech" },
  { name: "Terraform", vertical: "tech" },
  { name: "CI/CD", vertical: "tech" },
  { name: "Linux", vertical: "tech" },
  { name: "Microservices", vertical: "tech" },
  { name: "Deep Learning", vertical: "tech" },
  { name: "NLP", vertical: "tech" },
  { name: "Computer Vision", vertical: "tech" },
  { name: "MLOps", vertical: "tech" },
  { name: "Apache Spark", vertical: "tech" },
  { name: "ETL Pipelines", vertical: "tech" },
  { name: "PostgreSQL", vertical: "tech" },
  { name: "MongoDB", vertical: "tech" },
  { name: "Redis", vertical: "tech" },
  { name: "Penetration Testing", vertical: "tech" },
  { name: "Cloud Security", vertical: "tech" },
  { name: "QA Automation", vertical: "tech" },
  { name: "Selenium", vertical: "tech" },
  { name: "Agile / Scrum", vertical: "tech" },
  { name: "Git", vertical: "tech" },
  { name: "Data Science", vertical: "tech" },
  { name: "Blockchain", vertical: "tech" },
  // finance
  { name: "Financial Modeling", vertical: "finance" },
  { name: "Valuation", vertical: "finance" },
  { name: "Accounting", vertical: "finance" },
  { name: "Risk Analysis", vertical: "finance" },
  { name: "Excel / VBA", vertical: "finance" },
  { name: "Bloomberg Terminal", vertical: "finance" },
  { name: "Financial Reporting", vertical: "finance" },
  { name: "Audit", vertical: "finance" },
  { name: "Regulatory Compliance", vertical: "finance" },
  { name: "Credit Analysis", vertical: "finance" },
  { name: "Treasury", vertical: "finance" },
  { name: "M&A", vertical: "finance" },
  { name: "Portfolio Management", vertical: "finance" },
  { name: "Taxation", vertical: "finance" },
  { name: "IFRS", vertical: "finance" },
  { name: "FP&A", vertical: "finance" },
  { name: "Budgeting & Forecasting", vertical: "finance" },
  { name: "Equity Research", vertical: "finance" },
  { name: "Fixed Income", vertical: "finance" },
  { name: "Derivatives", vertical: "finance" },
  { name: "Private Equity", vertical: "finance" },
  { name: "Venture Capital", vertical: "finance" },
  { name: "Hedge Funds", vertical: "finance" },
  { name: "KYC / AML", vertical: "finance" },
  { name: "Internal Controls", vertical: "finance" },
  { name: "Corporate Finance", vertical: "finance" },
  { name: "Quantitative Analysis", vertical: "finance" },
  { name: "Fund Accounting", vertical: "finance" },
  { name: "Management Accounting", vertical: "finance" },
  { name: "Capital Markets", vertical: "finance" },
  { name: "Trade Finance", vertical: "finance" },
  { name: "Wealth Management", vertical: "finance" },
  { name: "ESG Reporting", vertical: "finance" },
  { name: "Actuarial Analysis", vertical: "finance" },
  { name: "Insurance Underwriting", vertical: "finance" },
  { name: "Investor Relations", vertical: "finance" },
  // marketing
  { name: "SEO", vertical: "marketing" },
  { name: "Content Strategy", vertical: "marketing" },
  { name: "Paid Acquisition", vertical: "marketing" },
  { name: "Marketing Analytics", vertical: "marketing" },
  { name: "Brand Strategy", vertical: "marketing" },
  { name: "Copywriting", vertical: "marketing" },
  { name: "Social Media", vertical: "marketing" },
  { name: "Email / CRM Marketing", vertical: "marketing" },
  { name: "Event Marketing", vertical: "marketing" },
  { name: "Market Research", vertical: "marketing" },
  { name: "Growth Strategy", vertical: "marketing" },
  { name: "Media Buying", vertical: "marketing" },
  { name: "Influencer Marketing", vertical: "marketing" },
  { name: "Marketing Automation", vertical: "marketing" },
  { name: "Google Analytics", vertical: "marketing" },
  { name: "Google Ads", vertical: "marketing" },
  { name: "Meta Ads", vertical: "marketing" },
  { name: "TikTok Marketing", vertical: "marketing" },
  { name: "WeChat / RED Marketing", vertical: "marketing" },
  { name: "Community Management", vertical: "marketing" },
  { name: "Affiliate Marketing", vertical: "marketing" },
  { name: "A/B Testing", vertical: "marketing" },
  { name: "Conversion Rate Optimization", vertical: "marketing" },
  { name: "Marketing Strategy", vertical: "marketing" },
  { name: "Product Marketing", vertical: "marketing" },
  { name: "Lifecycle Marketing", vertical: "marketing" },
  { name: "Partnership Marketing", vertical: "marketing" },
  { name: "eCommerce Marketing", vertical: "marketing" },
  { name: "App Store Optimization", vertical: "marketing" },
  { name: "Video Marketing", vertical: "marketing" },
  { name: "Display Advertising", vertical: "marketing" },
  { name: "Programmatic Advertising", vertical: "marketing" },
  { name: "Marketing Attribution", vertical: "marketing" },
  { name: "Customer Segmentation", vertical: "marketing" },
  { name: "Go-To-Market Strategy", vertical: "marketing" },
  // design
  { name: "UI Design", vertical: "design" },
  { name: "UX Research", vertical: "design" },
  { name: "Figma", vertical: "design" },
  { name: "Design Systems", vertical: "design" },
  { name: "Prototyping", vertical: "design" },
  { name: "Visual Design", vertical: "design" },
  { name: "Motion Design", vertical: "design" },
  { name: "Illustration", vertical: "design" },
  { name: "Interaction Design", vertical: "design" },
  { name: "Branding", vertical: "design" },
  { name: "3D Design", vertical: "design" },
  { name: "Adobe Creative Suite", vertical: "design" },
  { name: "Sketch", vertical: "design" },
  { name: "Adobe Photoshop", vertical: "design" },
  { name: "Adobe Illustrator", vertical: "design" },
  { name: "After Effects", vertical: "design" },
  { name: "Blender", vertical: "design" },
  { name: "Cinema 4D", vertical: "design" },
  { name: "Webflow", vertical: "design" },
  { name: "Framer", vertical: "design" },
  { name: "Wireframing", vertical: "design" },
  { name: "User Journey Mapping", vertical: "design" },
  { name: "Usability Testing", vertical: "design" },
  { name: "Accessibility (WCAG)", vertical: "design" },
  { name: "Typography", vertical: "design" },
  { name: "Iconography", vertical: "design" },
  { name: "Packaging Design", vertical: "design" },
  { name: "Print Design", vertical: "design" },
  { name: "Design Thinking", vertical: "design" },
  { name: "Service Design", vertical: "design" },
  { name: "Information Architecture", vertical: "design" },
  { name: "Design Ops", vertical: "design" },
  { name: "Art Direction", vertical: "design" },
  { name: "Storyboarding", vertical: "design" },
  // ops
  { name: "Project Management", vertical: "ops" },
  { name: "Supply Chain", vertical: "ops" },
  { name: "Process Improvement", vertical: "ops" },
  { name: "Logistics", vertical: "ops" },
  { name: "Vendor Management", vertical: "ops" },
  { name: "Data Analysis", vertical: "ops" },
  { name: "Procurement", vertical: "ops" },
  { name: "Inventory Management", vertical: "ops" },
  { name: "Quality Assurance", vertical: "ops" },
  { name: "Lean / Six Sigma", vertical: "ops" },
  { name: "ERP Systems", vertical: "ops" },
  { name: "Demand Planning", vertical: "ops" },
  { name: "Warehouse Management", vertical: "ops" },
  { name: "Freight Forwarding", vertical: "ops" },
  { name: "Customs Clearance", vertical: "ops" },
  { name: "Fleet Management", vertical: "ops" },
  { name: "Production Planning", vertical: "ops" },
  { name: "Sales & Operations Planning", vertical: "ops" },
  { name: "Continuous Improvement", vertical: "ops" },
  { name: "Kaizen", vertical: "ops" },
  { name: "Contract Management", vertical: "ops" },
  { name: "KPI Reporting", vertical: "ops" },
  { name: "Risk Management", vertical: "ops" },
  { name: "Business Continuity Planning", vertical: "ops" },
  { name: "SAP", vertical: "ops" },
  { name: "Oracle ERP", vertical: "ops" },
  { name: "Category Management", vertical: "ops" },
  { name: "Strategic Sourcing", vertical: "ops" },
  { name: "Cost Reduction", vertical: "ops" },
  { name: "Order Fulfillment", vertical: "ops" },
  { name: "Last-Mile Delivery", vertical: "ops" },
  { name: "Capacity Planning", vertical: "ops" },
  // legal
  { name: "Contract Drafting", vertical: "legal" },
  { name: "Legal Research", vertical: "legal" },
  { name: "Corporate Law", vertical: "legal" },
  { name: "Litigation", vertical: "legal" },
  { name: "Regulatory Affairs", vertical: "legal" },
  { name: "Company Secretarial", vertical: "legal" },
  { name: "IP Law", vertical: "legal" },
  { name: "Due Diligence", vertical: "legal" },
  { name: "Employment Law", vertical: "legal" },
  { name: "Data Privacy", vertical: "legal" },
  { name: "Commercial Contracts", vertical: "legal" },
  { name: "Cross-Border Transactions", vertical: "legal" },
  { name: "Arbitration", vertical: "legal" },
  { name: "Mediation", vertical: "legal" },
  { name: "Civil Litigation", vertical: "legal" },
  { name: "Banking & Finance Law", vertical: "legal" },
  { name: "Securities Law", vertical: "legal" },
  { name: "Funds Law", vertical: "legal" },
  { name: "Competition Law", vertical: "legal" },
  { name: "Construction Law", vertical: "legal" },
  { name: "Conveyancing", vertical: "legal" },
  { name: "Trademark Law", vertical: "legal" },
  { name: "Patent Law", vertical: "legal" },
  { name: "PDPO / GDPR Compliance", vertical: "legal" },
  { name: "Legal Operations", vertical: "legal" },
  { name: "eDiscovery", vertical: "legal" },
  { name: "Regulatory Investigations", vertical: "legal" },
  { name: "Corporate Governance", vertical: "legal" },
  // healthcare
  { name: "Patient Care", vertical: "healthcare" },
  { name: "Clinical Research", vertical: "healthcare" },
  { name: "Pharmacology", vertical: "healthcare" },
  { name: "Medical Devices", vertical: "healthcare" },
  { name: "Health Informatics", vertical: "healthcare" },
  { name: "Regulatory Submissions", vertical: "healthcare" },
  { name: "Physiotherapy", vertical: "healthcare" },
  { name: "Nursing", vertical: "healthcare" },
  { name: "Medical Writing", vertical: "healthcare" },
  { name: "Public Health", vertical: "healthcare" },
  { name: "ICU / Critical Care", vertical: "healthcare" },
  { name: "Emergency Care", vertical: "healthcare" },
  { name: "Paediatric Care", vertical: "healthcare" },
  { name: "Geriatric Care", vertical: "healthcare" },
  { name: "Oncology", vertical: "healthcare" },
  { name: "Surgical Nursing", vertical: "healthcare" },
  { name: "Midwifery", vertical: "healthcare" },
  { name: "Infection Control", vertical: "healthcare" },
  { name: "Clinical Trials (GCP)", vertical: "healthcare" },
  { name: "Pharmacovigilance", vertical: "healthcare" },
  { name: "Medical Coding", vertical: "healthcare" },
  { name: "Telemedicine", vertical: "healthcare" },
  { name: "Occupational Therapy", vertical: "healthcare" },
  { name: "Speech Therapy", vertical: "healthcare" },
  { name: "Radiography", vertical: "healthcare" },
  { name: "Laboratory Medicine", vertical: "healthcare" },
  { name: "Dietetics", vertical: "healthcare" },
  { name: "Mental Health Support", vertical: "healthcare" },
  // education
  { name: "Lesson Planning", vertical: "education" },
  { name: "Curriculum Design", vertical: "education" },
  { name: "Classroom Management", vertical: "education" },
  { name: "EAL / ESL Teaching", vertical: "education" },
  { name: "Student Assessment", vertical: "education" },
  { name: "Educational Technology", vertical: "education" },
  { name: "Special Educational Needs", vertical: "education" },
  { name: "Academic Counseling", vertical: "education" },
  { name: "IB / DSE Curriculum", vertical: "education" },
  { name: "Early Childhood Education", vertical: "education" },
  { name: "STEM Education", vertical: "education" },
  { name: "Phonics", vertical: "education" },
  { name: "Mandarin Teaching", vertical: "education" },
  { name: "Cantonese Teaching", vertical: "education" },
  { name: "English Literature", vertical: "education" },
  { name: "Mathematics Teaching", vertical: "education" },
  { name: "Science Teaching", vertical: "education" },
  { name: "Music Education", vertical: "education" },
  { name: "Physical Education", vertical: "education" },
  { name: "Drama Education", vertical: "education" },
  { name: "Montessori", vertical: "education" },
  { name: "IGCSE", vertical: "education" },
  { name: "A-Levels", vertical: "education" },
  { name: "AP Curriculum", vertical: "education" },
  { name: "University Admissions Counseling", vertical: "education" },
  { name: "Learning Management Systems", vertical: "education" },
  { name: "Student Welfare", vertical: "education" },
  { name: "Teacher Training", vertical: "education" },
  // sales
  { name: "Lead Generation", vertical: "sales" },
  { name: "Account Management", vertical: "sales" },
  { name: "Negotiation", vertical: "sales" },
  { name: "CRM (Salesforce)", vertical: "sales" },
  { name: "Solution Selling", vertical: "sales" },
  { name: "Sales Forecasting", vertical: "sales" },
  { name: "Channel Management", vertical: "sales" },
  { name: "Client Relationship Management", vertical: "sales" },
  { name: "Cold Outreach", vertical: "sales" },
  { name: "Territory Planning", vertical: "sales" },
  { name: "B2B Sales", vertical: "sales" },
  { name: "B2C Sales", vertical: "sales" },
  { name: "Enterprise Sales", vertical: "sales" },
  { name: "Inside Sales", vertical: "sales" },
  { name: "Field Sales", vertical: "sales" },
  { name: "SaaS Sales", vertical: "sales" },
  { name: "Retail Sales", vertical: "sales" },
  { name: "Channel Sales", vertical: "sales" },
  { name: "Sales Operations", vertical: "sales" },
  { name: "Revenue Operations", vertical: "sales" },
  { name: "Pipeline Management", vertical: "sales" },
  { name: "Upselling & Cross-Selling", vertical: "sales" },
  { name: "Customer Retention", vertical: "sales" },
  { name: "Sales Enablement", vertical: "sales" },
  { name: "HubSpot CRM", vertical: "sales" },
  { name: "Tender Management", vertical: "sales" },
  { name: "Distributor Management", vertical: "sales" },
  { name: "Quota Management", vertical: "sales" },
  // hr
  { name: "Recruitment", vertical: "hr" },
  { name: "Onboarding", vertical: "hr" },
  { name: "Compensation & Benefits", vertical: "hr" },
  { name: "Employee Relations", vertical: "hr" },
  { name: "HRIS", vertical: "hr" },
  { name: "Performance Management", vertical: "hr" },
  { name: "Learning & Development", vertical: "hr" },
  { name: "Talent Management", vertical: "hr" },
  { name: "Employment Ordinance", vertical: "hr" },
  { name: "Payroll", vertical: "hr" },
  { name: "Executive Search", vertical: "hr" },
  { name: "Technical Recruiting", vertical: "hr" },
  { name: "Campus Recruitment", vertical: "hr" },
  { name: "Employer Branding", vertical: "hr" },
  { name: "HR Analytics", vertical: "hr" },
  { name: "Workforce Planning", vertical: "hr" },
  { name: "Succession Planning", vertical: "hr" },
  { name: "Organizational Development", vertical: "hr" },
  { name: "Culture & Engagement", vertical: "hr" },
  { name: "Industrial Relations", vertical: "hr" },
  { name: "MPF Administration", vertical: "hr" },
  { name: "Visa & Work Permits", vertical: "hr" },
  { name: "Workday", vertical: "hr" },
  { name: "SAP SuccessFactors", vertical: "hr" },
  { name: "Grievance Handling", vertical: "hr" },
  { name: "Diversity & Inclusion", vertical: "hr" },
  { name: "Total Rewards", vertical: "hr" },
  { name: "HR Transformation", vertical: "hr" },
  // consulting
  { name: "Strategy Development", vertical: "consulting" },
  { name: "Market Entry", vertical: "consulting" },
  { name: "Business Case Development", vertical: "consulting" },
  { name: "Stakeholder Management", vertical: "consulting" },
  { name: "Change Management", vertical: "consulting" },
  { name: "Process Mapping", vertical: "consulting" },
  { name: "Data Visualization", vertical: "consulting" },
  { name: "Workshop Facilitation", vertical: "consulting" },
  { name: "Commercial Due Diligence", vertical: "consulting" },
  { name: "Storylining / Presentations", vertical: "consulting" },
  { name: "Operating Model Design", vertical: "consulting" },
  { name: "Cost Transformation", vertical: "consulting" },
  { name: "Digital Transformation", vertical: "consulting" },
  { name: "Post-Merger Integration", vertical: "consulting" },
  { name: "Pricing Strategy", vertical: "consulting" },
  { name: "Customer Insights", vertical: "consulting" },
  { name: "Competitive Analysis", vertical: "consulting" },
  { name: "Benchmarking", vertical: "consulting" },
  { name: "Proposal Writing", vertical: "consulting" },
  { name: "Project Scoping", vertical: "consulting" },
  { name: "Hypothesis-Driven Problem Solving", vertical: "consulting" },
  { name: "Executive Communication", vertical: "consulting" },
  { name: "Program Management", vertical: "consulting" },
  { name: "Agile Coaching", vertical: "consulting" },
  { name: "KPI Design", vertical: "consulting" },
  { name: "Market Sizing", vertical: "consulting" },
  { name: "Scenario Planning", vertical: "consulting" },
  { name: "Survey Design", vertical: "consulting" },
  // property
  { name: "Leasing", vertical: "property" },
  { name: "Property Management", vertical: "property" },
  { name: "Quantity Surveying", vertical: "property" },
  { name: "Building Surveying", vertical: "property" },
  { name: "Facilities Management", vertical: "property" },
  { name: "Asset Management", vertical: "property" },
  { name: "Property Valuation", vertical: "property" },
  { name: "Tenancy Law", vertical: "property" },
  { name: "Construction Contracts", vertical: "property" },
  { name: "BIM", vertical: "property" },
  { name: "Real Estate Investment", vertical: "property" },
  { name: "REITs", vertical: "property" },
  { name: "Land Acquisition", vertical: "property" },
  { name: "Development Management", vertical: "property" },
  { name: "Construction Project Management", vertical: "property" },
  { name: "Cost Estimation", vertical: "property" },
  { name: "Contract Administration", vertical: "property" },
  { name: "Fit-Out Management", vertical: "property" },
  { name: "Building Services", vertical: "property" },
  { name: "MEP Coordination", vertical: "property" },
  { name: "Site Supervision", vertical: "property" },
  { name: "Building Inspection", vertical: "property" },
  { name: "Property Marketing", vertical: "property" },
  { name: "Tenant Relations", vertical: "property" },
  { name: "Rent Review", vertical: "property" },
  { name: "BEAM Plus / Sustainability", vertical: "property" },
  { name: "AutoCAD", vertical: "property" },
  { name: "Land Use Planning", vertical: "property" },
  // media
  { name: "Journalism", vertical: "media" },
  { name: "Editing", vertical: "media" },
  { name: "Video Production", vertical: "media" },
  { name: "Public Relations", vertical: "media" },
  { name: "Media Relations", vertical: "media" },
  { name: "Scriptwriting", vertical: "media" },
  { name: "Photography", vertical: "media" },
  { name: "Podcast Production", vertical: "media" },
  { name: "Crisis Communications", vertical: "media" },
  { name: "Social Content", vertical: "media" },
  { name: "Copy Editing", vertical: "media" },
  { name: "Proofreading", vertical: "media" },
  { name: "News Writing", vertical: "media" },
  { name: "Feature Writing", vertical: "media" },
  { name: "Investigative Journalism", vertical: "media" },
  { name: "Broadcast Production", vertical: "media" },
  { name: "Live Streaming", vertical: "media" },
  { name: "Audio Engineering", vertical: "media" },
  { name: "Color Grading", vertical: "media" },
  { name: "Premiere Pro", vertical: "media" },
  { name: "Final Cut Pro", vertical: "media" },
  { name: "Documentary Production", vertical: "media" },
  { name: "Influencer Relations", vertical: "media" },
  { name: "Speechwriting", vertical: "media" },
  { name: "Internal Communications", vertical: "media" },
  { name: "Corporate Communications", vertical: "media" },
  { name: "Media Training", vertical: "media" },
  { name: "Content Localization", vertical: "media" },
];
