import Link from "next/link";

export const metadata = {
  title: "Privacy Policy · The Job Market",
};

// HK PDPO obligations this page is written against (engineering notes, not legal
// advice — have counsel review before launch):
//  - DPP1 (collection): collect only what's necessary for a stated purpose, and
//    tell the subject the purpose at/before collection. Drives the consent line
//    at sign-up and the "what we collect / why" sections below. We deliberately
//    minimise: the candidate feed ships only ranking-relevant columns, never
//    biodata (see /api/candidates/feed).
//  - DPP2 (accuracy/retention): keep data accurate and don't keep it longer than
//    necessary. Subjects can correct via Settings and delete via Settings.
//  - DPP3 (use limitation): no use beyond the stated purpose without fresh
//    consent. Aggregate/anonymised salary stats are covered by the Terms.
//  - DPP4 (security): safeguards against unauthorised access (auth, RLS,
//    service-key isolation, input validation).
//  - DPP5 (openness): this policy.
//  - DPP6 (access/correction): export via /api/me/export, correct via Settings.
const LAST_UPDATED = "23 June 2026";

const SECTIONS: { heading: string; body: string[] }[] = [
  {
    heading: "1. WHO WE ARE",
    body: [
      "The Job Market (the \"Platform\") is a talent marketplace operating in the Hong Kong technology vertical. This Privacy Policy explains what personal data we collect, why, how we use and protect it, and the rights you have over it. It should be read together with our Terms and Conditions.",
      "We handle personal data in line with the Personal Data (Privacy) Ordinance (Cap. 486) of Hong Kong.",
    ],
  },
  {
    heading: "2. DATA WE COLLECT",
    body: [
      "Account data: your name, email address, password (stored only as a salted hash), and role (candidate or employer).",
      "Candidate data: the experience, current salary, biodata you choose to provide (date of birth, sex, languages, citizenship), your job positions (role, location, work mode, desired salary), and your portfolio projects (titles, descriptions, links, uploaded files, and tagged skills).",
      "Employer data: your company profile (name, size, industry, website, headquarters, description) and your job openings.",
      "Activity data: pitches, matches, in-app chat messages, hire offers, and the reputation events generated by your activity. Limited technical and analytics data (for example, product usage events) may also be collected to operate and improve the Platform.",
    ],
  },
  {
    heading: "3. WHY WE USE IT",
    body: [
      "To provide the core service: ranking candidates for employers, surfacing job openings, generating composite scores and neutral salary references, and enabling pitches, matches, and chat.",
      "To operate your account, send transactional email (verification, password and email changes), and, where you have opted in, activity notifications.",
      "To keep the marketplace healthy and safe: anti-ghosting reputation signals, fraud and abuse prevention, and security monitoring.",
      "We collect only what is needed for these purposes. The candidate feed shown to employers excludes biodata and never includes your current salary.",
    ],
  },
  {
    heading: "4. LEGAL BASIS AND CONSENT",
    body: [
      "We process your data to perform the service you have signed up for, to meet legal obligations, and on the basis of the consent you give at registration. You may withdraw consent by closing your account, though some processing necessary to provide the service will end with it.",
    ],
  },
  {
    heading: "5. HOW IT IS SHARED",
    body: [
      "Candidate ranking and profile information is shown to employers with an active subscription so they can decide whether to pitch you. Your contact email is not exposed to employers through the feed.",
      "Employer profile information is shown to candidates who receive a pitch, so they can verify the sender's legitimacy before accepting.",
      "Anonymised and aggregated data, such as accepted-offer salaries, may power the market references shown to other users. These never include information that identifies you.",
      "We use third-party processors to run the Platform (hosting, database, email delivery, payments, and analytics). They act on our instructions and only to provide their service. We do not sell your personal data.",
    ],
  },
  {
    heading: "6. RETENTION",
    body: [
      "We keep your personal data for as long as your account is active and as needed to provide the service. When you delete your account, your profile, postings, portfolio, and chat content are removed. Anonymised salary observations that no longer identify you, and other parties' reputation history, may be retained as permitted by law.",
    ],
  },
  {
    heading: "7. SECURITY",
    body: [
      "We protect your data with authenticated access controls, row-level database policies, isolation of privileged keys to server-side code, server-side validation of all input, and signed, time-limited links for file downloads. No system is perfectly secure, but we work to safeguard your data against unauthorised access, loss, or misuse.",
    ],
  },
  {
    heading: "8. YOUR RIGHTS",
    body: [
      "Access and portability: you can download all the personal data we hold about you at any time from Settings, as a single JSON file.",
      "Correction: you can review and update your profile, biodata, postings, and portfolio from Settings.",
      "Erasure: you can delete your account, and the personal data associated with it, from Settings → Danger Zone.",
      "Under the PDPO you also have the right to ask about, and request correction of, the data we hold. Contact us using the details below to exercise any of these rights.",
    ],
  },
  {
    heading: "9. CHANGES",
    body: [
      "We may update this Policy from time to time. Material changes will be reflected here with a new \"last updated\" date. Continued use of the Platform after changes take effect constitutes acceptance of the revised Policy.",
    ],
  },
  {
    heading: "10. CONTACT",
    body: [
      "Questions about this Policy, or requests to access or correct your data, can be directed to the Platform operator through the contact channels listed on the Platform.",
    ],
  },
];

export default function PrivacyPage() {
  return (
    <div className="panel p-8">
      <div className="mb-6">
        <Link href="/sign-up" className="link-up mono mb-1 inline-block" style={{ fontSize: 11 }}>
          ← BACK
        </Link>
        <h1
          className="mono"
          style={{ fontSize: 18, fontWeight: 700, color: "var(--up)", letterSpacing: "0.04em" }}
        >
          PRIVACY POLICY
        </h1>
        <p className="kicker mt-1">LAST UPDATED · {LAST_UPDATED}</p>
      </div>

      <div className="space-y-6">
        {SECTIONS.map((section) => (
          <section key={section.heading}>
            <h2
              className="mono mb-2"
              style={{ fontSize: 12, fontWeight: 700, color: "var(--text)", letterSpacing: "0.04em" }}
            >
              {section.heading}
            </h2>
            {section.body.map((para, i) => (
              <p
                key={i}
                className="mono mb-2"
                style={{ fontSize: 12, lineHeight: 1.6, color: "var(--text-2)" }}
              >
                {para}
              </p>
            ))}
          </section>
        ))}
      </div>

      <div className="hr my-6" />
      <p className="mono text-center" style={{ fontSize: 12, color: "var(--muted)" }}>
        <Link href="/terms" className="link-up">
          TERMS AND CONDITIONS
        </Link>
      </p>
    </div>
  );
}
